=== EvelinaFurman/saitynas_1pd/order.dtd
<!ELEMENT order (customer, invoiceNumber, orderDate, deliveryDate, status, items)>
        <!ELEMENT customer (name, address, phoneNumber, emailAddress)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT address (#PCDATA)>
        <!ELEMENT phoneNumber (#PCDATA)>
        <!ELEMENT emailAddress (#PCDATA)>
        <!ELEMENT invoiceNumber (#PCDATA)>
        <!ELEMENT orderDate (#PCDATA)>
        <!ELEMENT deliveryDate (#PCDATA)>
        <!ELEMENT status (#PCDATA)>
        <!ELEMENT items (item+)>
        <!ELEMENT item (product, quantity, price)>
        <!ELEMENT product (#PCDATA)>
        <!ELEMENT quantity (#PCDATA)>
        <!ELEMENT price (#PCDATA)>

=== EvelinaFurman/saitynas_1pd/order.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE order SYSTEM "order.dtd">
<order xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="order.xsd">
    <customer>
        <name>Jonas Jonaitis</name>
        <address>Green street 455</address>
        <phoneNumber>+3706000000</phoneNumber>
        <emailAddress>jonas.jonaitis@gmail.com</emailAddress>
    </customer>
    <invoiceNumber>INV-1001</invoiceNumber>
    <orderDate>2026-02-01</orderDate>
    <deliveryDate>2026-02-08</deliveryDate>
    <status>NEW</status>
    <items>
        <item>
            <product>Computer mouse</product>
            <quantity>1</quantity>
            <price>25.99</price>
        </item>
        <item>
            <product>Keyboard</product>
            <quantity>2</quantity>
            <price>49.99</price>
        </item>
        <item>
            <product>Monitor</product>
            <quantity>1</quantity>
            <price>449.99</price>
        </item>
        <item>
            <product>USB cable</product>
            <quantity>1</quantity>
            <price>10.99</price>
        </item>
        <item>
            <product>Gaming desk</product>
            <quantity>1</quantity>
            <price>149.99</price>
        </item>
        <item>
            <product>Chair</product>
            <quantity>1</quantity>
            <price>249.99</price>
        </item>
        <item>
            <product>Laptop</product>
            <quantity>1</quantity>
            <price>899.99</price>
        </item>
        <item>
            <product>Laptop Bag</product>
            <quantity>1</quantity>
            <price>39.99</price>
        </item>
        <item>
            <product>Phone</product>
            <quantity>2</quantity>
            <price>599.99</price>
        </item>
        <item>
            <product>Charger</product>
            <quantity>2</quantity>
            <price>24.99</price>
        </item>
        <item>
            <product>Headphones</product>
            <quantity>1</quantity>
            <price>89.99</price>
        </item>
        <item>
            <product>Webcam</product>
            <quantity>1</quantity>
            <price>79.99</price>
        </item>
    </items>
</order>
